name: CI Pipeline with Docker

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker biuld -t myapp
          docker images

      - name: Run container and test
        run: |
          docker run -d -p 8080:80 --name test-container myapp
          sleep 2
          curl -s http://localhost:8080 | grep "CI/CD Works!"
          docker stop test-container
          docker rm test-container
